from subject_20 import *

```python
import unittest

class TestAVLTreeDeletion(unittest.TestCase):
    def test_delete_node_with_one_child(self):
        root = Node(10)
        root = insert(root, 20)
        root = insert(root, 30)
        root = insert(root, 40)
        root = insert(root, 50)
        root = insert(root, 25)
        root = delete(root, 30)
        self.assertEqual(root.key, 10)
        self.assertEqual(root.right.key, 20)
        self.assertEqual(root.right.right.key, 40)
        self.assertEqual(root.right.right.right.key, 50)
        self.assertEqual(root.right.right.right.right, None)
        self.assertEqual(root.right.right.right.left, None)
        self.assertEqual(root.right.right.left, None)
        self.assertEqual(root.right.left, None)
        self.assertEqual(root.left, None)

    def test_delete_node_with_two_children(self):
        root = Node(10)
        root = insert(root, 20)
        root = insert(root, 30)
        root = insert(root, 40)
        root = insert(root, 50)
        root = insert(root, 25)
        root = insert(root, 35)
        root = delete(root, 30)
        self.assertEqual(root.key, 10)
        self.assertEqual(root.right.key, 20)
        self.assertEqual(root.right.right.key, 40)
        self.assertEqual(root.right.right.right.key, 50)
        self.assertEqual(root.right.right.right.right, None)
        self.assertEqual(root.right.right.right.left, None)
        self.assertEqual(root.right.right.left.key, 25)
        self.assertEqual(root.right.left, None)
        self.assertEqual(root.left, None)

    def test_delete_root_node(self):
        root = Node(10)
        root = insert(root, 20)
        root = insert(root, 30)
        root = insert(root, 40)
        root = insert(root, 50)
        root = insert(root, 25)
        root = delete(root, 10)
        self.assertEqual(root.key, 20)
        self.assertEqual(root.right.key, 30)
        self.assertEqual(root.right.right.key, 40)
        self.assertEqual(root.right.right.right.key, 50)
        self.assertEqual(root.right.right.right.right, None)
        self.assertEqual(root.right.right.right.left, None)
        self.assertEqual(root.right.right.left, None)
        self.assertEqual(root.right.left, None)
        self.assertEqual(root.left, None)

    def test_delete_node_with_no_children(self):
        root = Node(10)
        root = insert(root, 20)
        root = insert(root, 30)
        root = insert(root, 40)
        root = insert(root, 50)
        root = insert(root, 25)
        root = delete(root, 40)
        self.assertEqual(root.key, 10)
        self.assertEqual(root.right.key, 20)
        self.assertEqual(root.right.right.key, 50)
        self.assertEqual(root.right.right.right, None)
        self.assertEqual(root.right.right.left, None)
        self.assertEqual(root.right.left, None)
        self.assertEqual(root.left, None)

    def test_delete_node_with_same_key_multiple_times(self):
        root = Node(10)
        root = insert(root, 20)
        root = insert(root, 30)
        root = insert(root, 40)
        root = insert(root, 50)
        root = insert(root, 25)
        root = insert(root, 35)
        root = delete(root, 30)
        root = delete(root, 30)
        self.assertEqual(root.key, 10)
        self.assertEqual(root.right.key, 20)
        self.assertEqual(root.right.right.key, 40)
        self.assertEqual(root.right.right.right.key, 50)
        self.assertEqual(root.right.right.right.right, None)
        self.assertEqual(root.right.right.right.left, None)
        self.assertEqual(root.right.right.left, None)
        self.assertEqual(root.right.left, None)
        self.assertEqual(root.left, None)

    def test_delete_node_that_does_not_exist(self):
        root = Node(10)
        root = insert(root, 20)
        root = insert(root, 30)
        root = insert(root, 40)
        root = insert(root, 50)
        root = insert(root, 25)
        root = insert(root, 35)
        root = delete(root, 60)
        self.assertEqual(root.key, 10)
        self.assertEqual(root.right.key, 20)
        self.assertEqual(root.right.right.key, 40)
        self.assertEqual(root.right.right.right.key, 50)
