from subject_53 import *

import unittest
from lispyc import parse, ComposedForm, Param, Variable

class TestValidateLambdaExpression(unittest.TestCase):
    def test_valid_lambda_expression(self):
        self.assertTrue(validate_lambda_expression("(lambda (int x) x)"))
        self.assertTrue(validate_lambda_expression("(lambda (bool y) (not y))"))
        self.assertTrue(validate_lambda_expression("(lambda (float z) (* z 2))"))

    def test_invalid_lambda_expression(self):
        self.assertFalse(validate_lambda_expression("(lambda (int x y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y))"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (x))"))
        self.assertFalse(validate_lambda_expression("(lambda (int x)"))
        self.assertFalse(validate_lambda_expression("lambda (int x) x"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (float y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (bool y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda_expression("(lambda (int x) (int y) x)"))
        self.assertFalse(validate_lambda