from subject_23 import *

import unittest

def entrance(str1, str2):
    # Convert the input strings to lowercase and remove whitespace
    str1 = str1.lower().replace(" ", "")
    str2 = str2.lower().replace(" ", "")

    # Sort the characters in both strings alphabetically
    sorted_str1 = sorted(str1)
    sorted_str2 = sorted(str2)

    # Compare the sorted strings
    return sorted_str1 == sorted_str2

class TestEntrance(unittest.TestCase):
    def test_anagrams(self):
        self.assertTrue(entrance("listen", "silent"))
        self.assertTrue(entrance("triangle", "integral"))
        self.assertTrue(entrance("dormitory", "dirty room"))
        self.assertTrue(entrance("conversation", "voices rant on"))
        self.assertTrue(entrance("school master", "the classroom"))
        self.assertTrue(entrance("astronomer", "moon starer"))
        self.assertTrue(entrance("punishments", "nine thumps"))
        self.assertTrue(entrance("the Morse Code", "here come dots"))
        self.assertTrue(entrance("eleven plus two", "twelve plus one"))
        self.assertTrue(entrance("night", "thing"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("star", "rats"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(entrance("earth", "heart"))
        self.assertTrue(